/* eslint-disable import/prefer-default-export */
export const BookingConstants = {
  ALL_MENTORS: 'ALL_MENTORS',
  GET_MENTOR_ID: 'GET_MENTOR_ID',
  ONE_MENTOR: 'ONE_MENTOR',
  CREATE_RESERVATION: 'CREATE_RESERVATION',
  ALL_RESERVATIONS: 'ALL_RESERVATIONS',
  ONE_RESERVATION: 'ONE_RESERVATION',
};
